const citiesFromDb = [
  "Clanton",
  "Evergreen",
  "Falkville",
  "Jasper",
  "Loxley",
  "McCalla",
  "Moody",
  "Muscle Shoals",
  "Ozark",
  "Prichard",
  "Shorter",
  "Steele",
  "Blytheville",
  "Jonesboro",
  "Little Rock",
  "Morrilton",
  "North Little Rock",
  "Ozark",
  "Palestine",
  "Prescott",
  "Searcy",
  "West Memphis",
  "Benson",
  "Buckeye",
  "Casa Grande",
  "Chandler ",
  "Gila Bend",
  "Joseph City",
  "Kingman",
  "Lake Havasu City",
  "Quartzsite",
  "Tolleson",
  "Williams",
  "Yuma",
  "Barstow",
  "Coachella",
  "Corning",
  "Lodi",
  "Lost Hills ",
  "Ripon ",
  "Santa Nella",
  "Tehachapi",
  "Tulare",
  "Bennett",
  "Buena Vista",
  "Burlington",
  "Eads",
  "Fountain",
  "Grand Junction",
  "Gunnison",
  "Hudson",
  "La Junta",
  "Lamar",
  "Lamar",
  "Monte Vista",
  "Pueblo",
  "Springfield",
  "Auburndale",
  "Cottondale",
  "Davenport",
  "Fort Pierce",
  "Liberal",
  "Fort Pierce",
  "Hawthorne",
  "Jacksonville",
  "Jasper",
  "Lee ",
  "Moore Haven",
  "Mossy Head",
  "North Fort Myers",
  "Ocala",
  "Ormond Beach ",
  "Brunswick",
  "Dublin ",
  "Emerson",
  "Hogansville",
  "Jackson",
  "Macon",
  "Richmond Hill ",
  "Thomson",
  "Tifton",
  "Waco ",
  "Clive",
  "Davenport",
  "Ellsworth",
  "Floyd",
  "Newton ",
  "Shelby",
  "Sioux City",
  "Heyburn ",
  "Idaho Falls",
  "Post Falls",
  "Dwight",
  "Greenup",
  "Greenville",
  "Hamel",
  "Ina",
  "Kankakee",
  "Knoxville",
  "Le Roy ",
  "New Baden",
  "Oglesby",
  "Roscoe",
  "South Holland",
  "South Jacksonville",
  "Utica ",
  "Williamsville",
  "Angola",
  "Belleville",
  "Demotte",
  "Gary",
  "Haubstadt",
  "Knightstown",
  "Marion",
  "Memphis ",
  "Pendleton",
  "Pittsboro",
  "Plymouth",
  "Richmond ",
  "Saint Paul ",
  "Terre Haute",
  "Whiteland",
  "Whitestown",
  "Woodburn",
  "Arkansas City",
  "Belleville",
  "Chanute",
  "Colby",
  "Cunningham",
  "Dodge City",
  "Dodge City",
  "Dodge City",
  "Ellis",
  "Garden City",
  "Great Bend",
  "Hays",
  "Holcomb",
  "Liberal",
  "McPherson",
  "Meade",
  "Norton",
  "Ottawa",
  "Phillipsburg",
  "Pratt",
  "Scott City",
  "South Hutchinson",
  "Syracuse",
  "Calvert City ",
  "Corbin",
  "Grayson",
  "Horse Cave",
  "Richmond",
  "Sadieville",
  "Shepherdsville",
  "Sparta",
  "Waddy ",
  "Duson",
  "Greenwood",
  "Lake Charles",
  "Minden ",
  "Port Allen",
  "Port Barre",
  "Tallulah",
  "Vinton",
  "Cumberland",
  "Hagerstown",
  "Marshall ",
  "Albert Lea",
  "Bevier",
  "Bloomsdale",
  "Boonville",
  "Bridgeton",
  "Eagleville",
  "Harrisonville",
  "Joplin",
  "Matthews   ",
  "Neosho",
  "New London",
  "Rolla ",
  "Saint Joseph",
  "Saint Louis",
  "Sikeston",
  "Strafford",
  "Batesville",
  "Biloxi",
  "Canton",
  "Columbus",
  "Flowood",
  "Gulfport",
  "Indianola",
  "Lake",
  "Magee",
  "McComb",
  "Poplarville",
  "Toomsuba ",
  "Tupelo",
  "West Point",
  "Hardin",
  "Dunn",
  "Marion",
  "Salisbury",
  "Fargo",
  "Williston",
  "Aurora ",
  "Norfolk",
  "North Platte",
  "Sidney",
  "Syracuse",
  "Valley",
  "Bordentown",
  "Albuquerque",
  "Albuquerque",
  "Clayton",
  "Clovis",
  "Gallup",
  "Las Cruces",
  "Lordsburg",
  "Milan",
  "Santa Rosa",
  "Tucumcari",
  "Ely",
  "Fernley",
  "Las Vegas ",
  "Wells ",
  "Binghamton",
  "Canaan",
  "Bidwell",
  "Burbank",
  "Circleville",
  "Conneaut",
  "Dayton",
  "Hubbard",
  "Jeffersonville ",
  "North Baltimore",
  "Perrysburg",
  "Springfield",
  "Upper Sandusky",
  "Zanesville",
  "Ada",
  "Ada",
  "Altus",
  "Alva",
  "Ardmore",
  "Ardmore",
  "Atoka",
  "Beaver",
  "Boise City",
  "Broken Bow",
  "Buffalo",
  "Chickasha",
  "Chickasha",
  "Choctaw",
  "Chouteau",
  "Clinton",
  "Colbert ",
  "Comanche",
  "Crescent",
  "Duncan",
  "Durant",
  "Durant",
  "El Reno",
  "Elk City",
  "Elk City",
  "Enid",
  "Erick",
  "Eufaula",
  "Fairview",
  "Guthrie",
  "Guthrie",
  "Guthrie",
  "Guymon",
  "Hennessey",
  "Henryetta",
  "Hinton ",
  "Hollis",
  "Hooker",
  "Kingfisher",
  "Lawton",
  "Lindsay",
  "Madill",
  "Mangum",
  "Marlow",
  "McLoud",
  "Miami",
  "Norman",
  "Nowata",
  "Okemah",
  "Oklahoma City",
  "Oklahoma City",
  "Oklahoma City",
  "Oklahoma City",
  "Oklahoma City",
  "Okmulgee",
  "Pauls Valley",
  "Pauls Valley",
  "Purcell",
  "Seminole",
  "Shawnee",
  "Tahlequah",
  "Tecumseh",
  "Texhoma",
  "Tonkawa ",
  "Union City",
  "Valliant",
  "Watonga",
  "Webbers Falls",
  "West Siloam Springs",
  "Woodward",
  "Woodward",
  "Yukon",
  "Boardman",
  "Ontario",
  "Roseburg",
  "Troutdale",
  "Carlisle",
  "Hamburg",
  "Jonestown ",
  "Londonderry",
  "Mifflinville ",
  "Blacksburg",
  "Cayce",
  "Dillon",
  "Fair Play",
  "Fort Mill",
  "Lexington",
  "Newberry",
  "Orangeburg ",
  "Box Elder",
  "Sioux Falls",
  "Baxter ",
  "Charleston",
  "Christiana",
  "Columbia",
  "Dandridge",
  "Dickson",
  "Dyersburg",
  "Jackson",
  "Lenoir City",
  "Memphis",
  "Nashville",
  "Nickajack Lake",
  "White House",
  "Amarillo",
  "Amarillo",
  "Amarillo",
  "Andrews",
  "Angleton",
  "Anna",
  "Anthony",
  "Baird",
  "Baytown",
  "Claude",
  "Cleveland ",
  "Comfort",
  "Dallas",
  "Deer Park",
  "Denton",
  "Domino",
  "Dumas",
  "Edinburg",
  "Edna",
  "El Paso",
  "Encinal",
  "Fairfield",
  "Fort Stockton",
  "Fort Worth",
  "Hearne",
  "Hereford",
  "Hillsboro",
  "Houston",
  "Houston",
  "Hungerford",
  "Hutchins",
  "Italy",
  "Katy",
  "Kingsville ",
  "Leary",
  "Lubbock",
  "Lufkin",
  "Luling",
  "Memphis",
  "Midland",
  "Midlothian",
  "Mount Vernon",
  "Natalia",
  "Odessa ",
  "Paris",
  "Pecos",
  "Quanah",
  "Ranger",
  "Rhome",
  "Rockwall",
  "San Antonio",
  "Seguin",
  "Sinton",
  "Sweetwater",
  "Three Rivers",
  "Van",
  "Van",
  "Van Horn",
  "Weatherford",
  "Weimar",
  "Wichita Falls",
  "Willis",
  "Brigham City",
  "Cedar City ",
  "Salina",
  "Salt Lake City",
  "Springville",
  "Franklin",
  "Lambsburg",
  "Max Meadows",
  "Meadowview",
  "Ruther Glen",
  "Skippers",
  "South Hill",
  "Tom's Brook",
  "Ellensburg",
  "Napavine",
  "Prosser",
  "Ritzville",
  "Tacoma",
  "Dekorra - Poynette",
  "Fond du Lac",
  "Menomonie",
  "Oak Creek",
  "Oakdale",
  "Sheboygan",
  "Ripley",
  "Cheyenne",
  "Wamsutter",
];

const set = new Set(citiesFromDb);
const uniqArray = Array.from(set);

const allData = {
  states: [
    "AL",
    "AR",
    "AZ",
    "CA",
    "CO",
    "FL",
    "KS",
    "GA",
    "IA",
    "ID",
    "IL",
    "LA",
    "MD",
    "MI",
    "MN",
    "MO",
    "MS",
    "MT",
    "NC",
    "ND",
    "NE",
    "NJ",
    "NM",
    "NV",
    "NY",
    "OH",
    "OK",
    "OR",
    "PA",
    "SC",
    "TN",
    "TX",
    "UT",
    "VA",
    "WA",
    "WI",
    "WV",
    "WY",
  ],
  cities: uniqArray,
  highways: [
    "I-65",
    "I-22",
    "I-10",
    "I-20",
    "Hwy 72A",
    "HWY 231",
    "I-85",
    "I-59",
    "I-55",
    "Hwy 63",
    "I-30",
    "I-40",
    "HWY 67",
    "I-8",
    "I-15",
    "I-5",
    "Hwy 99",
    "Hwy 58",
    "I-70",
    "Hwy 24",
    "Hwy 287",
    "I-76",
    "Hwy 287/50",
    "I-25",
    "I-4",
    "I-95",
    "Hwy 301",
    "I-75",
    "Hwy 27",
    "I-16",
    "I-80",
    "I-35",
    "Hwy 18",
    "I-29",
    "I-84",
    "I-90",
    "I-57",
    "I-74",
    "I-64",
    "I-39",
    "I-94",
    "I-72",
    "I-69",
    "Hwy 30",
    "Hwy 41",
    "Hwy 81",
    "Hwy 169",
    "Hwy 400",
    "HWY 50",
    "Hwy 50",
    "Hwy 54",
    "I-135",
    "Hwy 36",
    "HWY 83",
    "I-24",
    "I-71",
    "Hwy 190",
    "I-68",
    "I-81",
    "Hwy 370",
    "I-49",
    "I-44",
    "Hwy 61",
    "Hwy 60",
    "Hwy 82",
    "Hwy 49",
    "Hwy 45A",
    "Hwy 2",
    "Hwy 275",
    "I-295",
    "Hwy 87",
    "Hwy 50/93",
    "Hwy 35",
    "Hwy 23",
    "I-280",
    "Hwy 30/23",
    "Hwy 69",
    "Hwy 412",
    "Hwy 74",
    "Hwy 19/76",
    "Hwy 75",
    "Hwy 70",
    "I-78",
    "Hwy 283",
    "I-77",
    "I-26",
    "I-155",
    "I-240",
    "I-27",
    "Hwy 385",
    "Hwy 288",
    "Hwy 225",
    "Hwy 59",
    "HWY 287",
    "Hwy 281",
    "I-45",
    "I-35W",
    "Hwy 6",
    "Loop 610",
    "I-35E",
    "Hwy 77",
    "Hwy 59/69/Loop 287",
    "Hwy 67",
    "Hwy 271",
    "I-37",
    "I-82",
    "I-41",
    "I-4",
  ],
  cityByState: [
    {
      id: 0,
      cities: [
        "Clanton",
        "Evergreen",
        "Falkville",
        "Jasper",
        "Loxley",
        "McCalla",
        "Moody",
        "Muscle Shoals",
        "Ozark",
        "Prichard",
        "Shorter",
        "Clanton",
        "Evergreen",
        "Falkville",
        "Jasper",
        "Loxley",
        "McCalla",
        "Moody",
        "Muscle Shoals",
        "Ozark",
        "Prichard",
        "Shorter",
        "Steele",
      ],
    },
    {
      id: 1,
      cities: [
        "Blytheville",
        "Jonesboro",
        "Little Rock",
        "Morrilton",
        "North Little Rock",
        "Ozark",
        "Palestine",
        "Prescott",
        "Searcy",
        "West Memphis",
      ],
    },
    {
      id: 2,
      cities: [
        "Benson",
        "Buckeye",
        "Casa Grande",
        "Chandler",
        "Gila Bend",
        "Joseph City",
        "Kingman",
        "Lake Havasu City",
        "Quartzsite",
        "Tolleson",
        "Williams",
        "Yuma",
      ],
    },
    {
      id: 3,
      cities: [
        "Barstow",
        "Coachella",
        "Corning",
        "Lodi",
        "Lost Hills",
        "Ripon",
        "Santa Nella",
        "Tehachapi",
        "Tulare",
      ],
    },
    {
      id: 4,
      cities: [
        "Bennett",
        "Buena Vista",
        "Burlington",
        "Eads",
        "Fountain",
        "Grand Junction",
        "Gunnison",
        "Hudson",
        "La Junta",
        "Lamar",
        "Lamar",
        "Monte Vista",
        "Pueblo",
        "Springfield",
      ],
    },
    {
      id: 5,
      cities: [
        "Auburndale",
        "Cottondale",
        "Davenport",
        "Fort Pierce",
        "Fort Pierce",
        "Hawthorne",
        "Jacksonville",
        "Jasper",
        "Lee",
        "Moore Haven",
        "Mossy Head",
        "North Fort Myers",
        "Ocala",
        "Ormond Beach",
      ],
    },
    {
      id: 6,
      cities: [
        "Liberal",
        "Arkansas City",
        "Belleville",
        "Chanute",
        "Colby",
        "Cunningham",
        "Dodge City",
        "Dodge City",
        "Dodge City",
        "Ellis",
        "Garden City",
        "Great Bend",
        "Hays",
        "Holcomb",
        "Liberal",
        "McPherson",
        "Meade",
        "Norton",
        "Ottawa",
        "Phillipsburg",
        "Pratt",
        "Scott City",
        "South Hutchinson",
        "Syracuse",
      ],
    },
    {
      id: 7,
      cities: [
        "Brunswick",
        "Dublin",
        "Emerson",
        "Hogansville",
        "Jackson",
        "Macon",
        "Richmond Hill",
        "Thomson",
        "Tifton",
        "Waco",
      ],
    },
    {
      id: 8,
      cities: [
        "Clive",
        "Davenport",
        "Ellsworth",
        "Floyd",
        "Newton",
        "Shelby",
        "Sioux City",
      ],
    },
    {
      id: 9,
      cities: ["Heyburn", "Idaho Falls", "Post Falls"],
    },
    {
      id: 10,
      cities: [
        "Dwight",
        "Greenup",
        "Greenville",
        "Hamel",
        "Ina",
        "Kankakee",
        "Knoxville",
        "Le Roy",
        "New Baden",
        "Oglesby",
        "Roscoe",
        "South Holland",
        "South Jacksonville",
        "Utica",
        "Williamsville",
      ],
    },
    {
      id: 11,
      cities: [
        "Angola",
        "Belleville",
        "Demotte",
        "Gary",
        "Haubstadt",
        "Knightstown",
        "Marion",
        "Memphis",
        "Pendleton",
        "Pittsboro",
        "Plymouth",
        "Richmond",
        "Saint Paul",
        "Terre Haute",
        "Whiteland",
        "Whitestown",
        "Woodburn",
      ],
    },
    {
      id: 12,
      cities: [
        "Duson",
        "Greenwood",
        "Lake Charles",
        "Minden",
        "Port Allen",
        "Port Barre",
        "Tallulah",
        "Vinton",
      ],
    },
    { id: 13, cities: ["Cumberland", "Hagerstown"] },
    { id: 14, cities: ["Marshall"] },
    { id: 15, cities: ["Albert Lea"] },
    {
      id: 16,
      cities: [
        "Bevier",
        "Bloomsdale",
        "Boonville",
        "Bridgeton",
        "Eagleville",
        "Harrisonville",
        "Joplin",
        "Matthews",
        "Neosho",
        "New London",
        "Rolla",
        "Saint Joseph",
        "Saint Louis",
        "Sikeston",
        "Strafford",
      ],
    },
    {
      id: 17,
      cities: [
        "Batesville",
        "Biloxi",
        "Canton",
        "Columbus",
        "Flowood",
        "Gulfport",
        "Indianola",
        "Lake",
        "Magee",
        "McComb",
        "Poplarville",
        "Toomsuba",
        "Tupelo",
        "West Point",
      ],
    },
    { id: 18, cities: ["Hardin"] },
    {
      id: 19,
      cities: ["Dunn", "Marion", "Salisbury"],
    },
    { id: 20, cities: ["Fargo", "Williston"] },
    {
      id: 21,
      cities: [
        "Aurora",
        "Norfolk",
        "North Platte",
        "Sidney",
        "Syracuse",
        "Valley",
      ],
    },
    { id: 22, cities: ["Bordentown"] },
    {
      id: 23,
      cities: [
        "Albuquerque",
        "Albuquerque",
        "Clayton",
        "Clovis",
        "Gallup",
        "Las Cruces",
        "Lordsburg",
        "Milan",
        "Santa Rosa",
        "Tucumcari",
      ],
    },
    {
      id: 24,
      cities: ["Ely", "Fernley", "Las Vegas", "Wells"],
    },
    { id: 25, cities: ["Binghamton", "Canaan"] },
    {
      id: 26,
      cities: [
        "Bidwell",
        "Burbank",
        "Circleville",
        "Conneaut",
        "Dayton",
        "Hubbard",
        "Jeffersonville",
        "North Baltimore",
        "Perrysburg",
        "Springfield",
        "Upper Sandusky",
        "Zanesville",
      ],
    },
    {
      id: 27,
      cities: [
        "Ada",
        "Ada",
        "Altus",
        "Alva",
        "Ardmore",
        "Ardmore",
        "Atoka",
        "Beaver",
        "Boise City",
        "Broken Bow",
        "Buffalo",
        "Chickasha",
        "Chickasha",
        "Choctaw",
        "Chouteau",
        "Clinton",
        "Colbert ",
        "Comanche",
        "Crescent",
        "Duncan",
        "Durant",
        "Durant",
        "El Reno",
        "Elk City",
        "Elk City",
        "Enid",
        "Erick",
        "Eufaula",
        "Fairview",
        "Guthrie",
        "Guthrie",
        "Guthrie",
        "Guymon",
        "Hennessey",
        "Henryetta",
        "Hinton ",
        "Hollis",
        "Hooker",
        "Kingfisher",
        "Lawton",
        "Lindsay",
        "Madill",
        "Mangum",
        "Marlow",
        "Marlow",
        "McLoud",
        "Miami",
        "Norman",
        "Nowata",
        "Okemah",
        "Oklahoma City",
        "Oklahoma City",
        "Oklahoma City",
        "Oklahoma City",
        "Oklahoma City",
        "Okmulgee",
        "Pauls Valley",
        "Pauls Valley",
        "Purcell",
        "Seminole",
        "Shawnee",
        "Tahlequah",
        "Tecumseh",
        "Texhoma",
        "Tonkawa ",
        "Union City",
        "Valliant",
        "Watonga",
        "Webbers Falls",
        "West Siloam Springs",
        "Woodward",
        "Woodward",
        "Yukon",
      ],
    },
    {
      id: 28,
      cities: ["Boardman", "Ontario", "Roseburg", "Troutdale"],
    },
    {
      id: 29,
      cities: ["Boardman", "Ontario", "Roseburg", "Troutdale"],
    },
    {
      id: 30,
      cities: [
        "Carlisle",
        "Hamburg",
        "Jonestown",
        "Londonderry",
        "Mifflinville",
      ],
    },
    {
      id: 31,
      cities: [
        "Blacksburg",
        "Cayce",
        "Dillon",
        "Fair Play",
        "Fort Mill",
        "Lexington",
        "Newberry",
        "Orangeburg",
      ],
    },
    {
      id: 32,
      cities: ["Box Elder", "Sioux Falls"],
    },
    {
      id: 33,
      cities: [
        "Baxter",
        "Charleston",
        "Christiana",
        "Columbia",
        "Dandridge",
        "Dickson",
        "Dyersburg",
        "Jackson",
        "Lenoir City",
        "Memphis",
        "Nashville",
        "Nickajack Lake",
        "White House",
      ],
    },
    {
      id: 34,
      cities: [
        "Amarillo",
        "Amarillo",
        "Amarillo",
        "Andrews",
        "Angleton",
        "Anna",
        "Anthony",
        "Baird",
        "Baytown",
        "Claude",
        "Cleveland",
        "Comfort",
        "Dallas",
        "Deer Park",
        "Denton",
        "Domino",
        "Dumas",
        "Edinburg",
        "Edna",
        "El Paso",
        "Encinal",
        "Fairfield",
        "Fort Stockton",
        "Fort Worth",
        "Hearne",
        "Hereford",
        "Hillsboro",
        "Houston",
        "Houston",
        "Hungerford",
        "Hutchins",
        "Italy",
        "Katy",
        "Kingsville",
        "Leary",
        "Lubbock",
        "Lufkin",
        "Luling",
        "Memphis",
        "Midland",
        "Midlothian",
        "Mount Vernon",
        "Natalia",
        "Odessa",
        "Paris",
        "Pecos",
        "Quanah",
        "Ranger",
        "Rhome",
        "Rockwall",
        "San Antonio",
        "Seguin",
        "Sinton",
        "Sweetwater",
        "Three Rivers",
        "Van",
        "Van",
        "Van Horn",
        "Weatherford",
        "Weimar",
        "Wichita Falls",
        "Willis",
      ],
    },
    {
      id: 35,
      cities: [
        "Brigham City",
        "Cedar City",
        "Salina",
        "Salt Lake City",
        "Springville",
      ],
    },
    {
      id: 36,
      cities: [
        "Franklin",
        "Lambsburg",
        "Max Meadows",
        "Meadowview",
        "Ruther Glen",
        "Skippers",
        "South Hill",
        "Tom's Brook",
      ],
    },
    {
      id: 37,
      cities: ["Ellensburg", "Napavine", "Prosser", "Ritzville", "Tacoma"],
    },
    {
      id: 38,
      cities: [
        "Dekorra - Poynette",
        "Fond du Lac",
        "Menomonie",
        "Oak Creek",
        "Oakdale",
        "Sheboygan",
      ],
    },
    { id: 39, cities: ["Ripley"] },
    { id: 40, cities: ["Cheyenne", "Wamsutter"] },
  ],
  highwaysByCity: [
    {
      id: 342,
      highways: ["I-40", "I-27"],
    },
    {
      id: 108,
      highways: ["I-70", "Hwy 81"],
    },
    {
      id: 59,
      highways: ["I-80", "I-4"],
    },
    { id: 60, highways: ["I-95", "I-95"] },
    { id: 369, highways: ["Loop 610", "I-45"] },
    { id: 76, highways: ["I-40", "I-75"] },
    { id: 3, highways: ["I-75", "I-22"] },
    { id: 113, highways: ["I-69", "I-40"] },
    { id: 338, highways: ["Hwy 287", "I-240"] },
    { id: 287, highways: ["I-44", "I-35", "I-40"] },
    { id: 8, highways: ["I-40", "HWY 231"] },
    { id: 151, highways: ["I-75", "I-70"] },
  ],
};

module.exports = { allData, citiesFromDb };
